name: Gradle Package

on:
  release:
    types: [created]
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-jar
        path: build/libs/*.jar

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: build-jar
        path: ./build

    - name: List files for debugging
      run: ls -al ./build

    - name: Create libs directory
      run: mkdir -p ./build/libs

    - name: Move JAR file
      run: mv ./build/*.jar ./build/libs/

    - name: List files in libs for debugging
      run: ls -al ./build/libs

    - name: Set version variable
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build/libs/ChestShop-1.0-SNAPSHOT.jar
        asset_name: ChestShop-${{ env.VERSION }}.jar
        asset_content_type: application/java-archive
